
export type Projects = {
  id : number,
  name : string,
  shortDescription : string,
  tags : string[],
  siteURL : string | null,
  githubURL : string | null,
  more? : string[][] 
}

const projectsES : Projects[] = [
  {
    id : 1,
    name : "Portafolio de proyectos",
    shortDescription : "Este portafolio de proyectos 😄",
    tags : ['React', 'NextJS', 'Typescript'],
    siteURL : '/',
    githubURL : 'https://github.com/danyrszz/personal-portfolio',
  },
  {
    id : 2,
    name : "Control de ingresos y gastos",
    shortDescription : "Aplicación personal para llevar el control de los ingresos y gastos generados por unidad taxi.",
    tags : ['React', 'CSS', 'Express', 'MongoDB'],
    siteURL : null,
    githubURL : 'https://github.com/danyrszz/expenses-incomes-tracker-app---MERN-stack',
    more : [
      ['title', 'Control de ingresos y gastos para taxi.' ],
      ['text','Esta app nació de la necesidad de llevar a cabo la gestión de los gastos y los ingresos generados por una unidad de taxi.'],
      ['text','El proyecto está desarrollado como un sistema web bajo el stack "MERN", haciendo uso de las tecnologías MongoDB, ExpressJS y React. Este sistema está desarrollado para uso personal. El frontend del proyecto se encuentra desplegado en render y el backend en vercel.'],
      ['text','Debido a que maneja información personal no está disponible su enlace, sin embargo muestro aquí algunas capturas del sistema que muestren su funcionamiento, y el código, por supuesto, se encuentra en Github.'],
      ['title','Secciones de la app.'],
      ['subtitle','Dashboard'],
      ['image','/blog-img/2/dash.png'],
      ['text','La página principal. Esta página muestra información general y los últimos 5 gastos y cuentas ingresadas.'],
      ['subtitle','Añadir cuenta y Añadir gasto.'],
      ['image','/blog-img/2/addspend.png'],
      ['text','Estas secciones permiten guardar la información en la base de datos a través de un sencillo y amigable formulario.'],
      ['subtitle','Historial > Cuentas'],
      ['image','/blog-img/2/bills.png'],
      ['text','Muestra las cuentas almacenadas por mes, permitiendo al usuario filtarar por mes y año. Una cuenta puede ser modificada o eliminada.'],
      ['subtitle','Historial > Gastos'],
      ['image','/blog-img/2/spends-desktop.png'],
      ['text','La página principal de los gastos muestra información de los ultimos 10 gastos registrados en la app. El usuario puede filtrar la información de varias formas posibles. Hacer clic en un gasto permite al usuario ir al formulario correspondiente para su edición o eliminación.'],
      ['text','La tabla de gastos es adaptable a pantallas para escritorio, tableta o teléfono inteligente.'],
      ['image','/blog-img/2/spends-tablet.png'],
      ['caption','Vista de tableta'],
      ['image','/blog-img/2/spends-mobile.png'],
      ['caption','Vista de teléfono inteligente'],
      ['subtitle','Filtro de gastos'],
      ['text','Esta ventana permite al usuario seleccionar hasta tres filtros diferentes, o combinarlos entre sí para buscar con precisión un gasto.'],
      ['image','/blog-img/2/filter.png'],
      ['caption','Vista de filtro sin seleccionar'],
      ['text',`Imaginemos que queremos filtrar los servicios que se le han hecho al auto, y ver aquellos que han costado menos de $1000 en lo que va del año 2023. Así es como el filtro se vería al realizar esta solicitud.`],
      ['image','/blog-img/2/threefilters.png'],
      ['text','...y así es como sería el resultado en pantalla.'],
      ['image','/blog-img/2/filteredspends.png'],
      ['subtitle','Activo'],
      ['text',`Por último, tenemos la pantalla de activo, que muestra una fotito del auto, junto con alguna información extra, mostrando las ganancias (seleccionada en la captura. En este caso son negativas porque aún no se han tenido ganancias) y el porcentaje actual de la recuperación de la inversión.`],
      ['image','/blog-img/2/asset.png'],
      ['title','Un poco más...'],
      ['text','Esta app esta hecha para gestionar solo un auto. Esto fue hecho así a propósito desde el diseño y desarrollo de la app. Hay dos razones principales:'],
      ['text','Uno: Quise mantener las cosas sencillas debido a que solamente tengo una unidad de taxi trabajando y solo una, así que necesitaba terminar este desarrollo rápidamente para poder comenzar a llevar a cabo el registro de mi información.'],
      ['text',`Segundo: Quise motivarme a utilizar tecnologías que no había usado antes. Como puedes ver en mis proyectos más abajo, principalmente había estado practicando el desarrollo frontend, usando algo de JS básico, HTML y CSS. Entonces quería practicar un poco más de react y entender mejor algunos conceptos para aplicarlos en este proyecto.`],
      ['text', `Asímismo esta es una aplicación fullstack terminada y desplegada, así que no solo tuve que codear el frontend, sino también el backend en Node conectándome a un cluster de MongoDb, y aprender un poco más de ambos mundos. `]
    ]
  },
  {
    id : 3,
    name : "Aplicación de Clima",
    shortDescription : "Permite desplegar la información del clima de una ubicación determinada por el usuario.",
    tags : ['React', 'CSS', 'APIs'],
    siteURL : 'https://danyrszz.github.io/weather-app-reactjs/',
    githubURL : 'https://github.com/danyrszz/weather-app-reactjs',
    more : [
      ['title', 'App de Clima' ],
      ['text','Esta una single-page app desarrollada con react. Se trata de un frontend que consume información de una API de clima, mostrándola en una interfaz agradable al usuario.'],
      ['subtitle','Barra lateral principal.'],
      ['text','En este apartado se muestra la información del clima de hoy (ícono de clima, temperatura, real feel, fecha y ubicación).'],
      ['subtitle','Barra lateral de búsqueda.'],
      ['text','Te permite buscar la ubicación que tu quieras para mostrar su información, o bien seleccionar la ubicación actual del dispositivo.'],
      ['subtitle','Barra de escala.'],
      ['text','Puedes cambiar entre grados centígrados o fahrenheit.'],
      ['subtitle','Clima semanal.'],
      ['text','Muestra la información del clima de los próximos seis días.'],
      ['subtitle','Highlights.'],
      ['text','Muestra información de viento, humedad, nubosidad y presión del aire.'],
    ]
  },
  {
    id : 4,
    name : "Juego de preguntas de países",
    shortDescription : "Quiz de países para devchallenges.io.",
    tags : ['React', 'CSS', 'APIs'],
    siteURL : 'https://danyrszz.github.io/country-quiz-react/',
    githubURL : 'https://github.com/danyrszz/country-quiz-react',
    more : [
      ['title', 'Country Quiz'],
      ['text', `Es un pequeño juego de preguntas de opción multiple. Funciona usando los datos de una API de países.`],
      ['text', `Tienes tres vidas. Tu puntuación se incrementa conforme respondes preguntas correctas, si te equivocas se te resta una vida. Tres errores y estás fuera.`],
      ['text', `¡Diviértete!`]
    ]
  },
  {
    id : 5,
    name : "Windbnb",
    shortDescription : "Un clon de la interfaz de airbnb reto de devchallenges.io.",
    tags : ['React', 'CSS'],
    siteURL : 'https://danyrszz.github.io/windbnb-reactJS-devchallenges/',
    githubURL : 'https://github.com/danyrszz/windbnb-reactJS-devchallenges',
    more : [
      ['title', `Windbnb`],
      ['text','Este reto estaba disponible en el sitio devchallenges.'],
      ['text',`Se trata de un clon de la interfaz de airbnb con un poco de funcionalidad. Hay algunos "alojamientos" de los cuales puedes filtrar por ubicación y número de huéspedes.`],
      ['text',`Algo simple pero un reto divertido para practicar algo de CSS y JS`],
    ]

  },
  {
    id : 6,
    name : "Generador aleatorio de consejos",
    shortDescription : "Aplicación que genera una frase aleatoria. Reto para frontendmentor.",
    tags : ['Javascript', 'HTML', 'SASS'],
    siteURL : 'https://danyrszz.github.io/FM-advice-generator-app/',
    githubURL : 'https://github.com/danyrszz/FM-advice-generator-app',
  },
  {
    id : 7,
    name : "Retos de Codewars",
    shortDescription : "Repositorio de algunos retos del sitio codewars.",
    tags : ['Javascript'],
    siteURL : null,
    githubURL : 'https://github.com/danyrszz/codewars',
  },
  {
    id : 8,
    name : "Conteo regresivo prelanzamiento",
    shortDescription : "Conteo regresivo previo a lanzamiento para sitio web. Desarrollado para frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/FM-launch-countdown-timer/',
    githubURL : 'https://github.com/danyrszz/FM-launch-countdown-timer',
  },
  {
    id : 9,
    name : "Calculadora de propinas",
    shortDescription : "Calculadora interactiva de propinas basadas en un precio total. Diseño para frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/tip-calculator-vanillaJS/',
    githubURL : 'https://github.com/danyrszz/tip-calculator-vanillaJS',
  },
  {
    id : 10,
    name : "Diseño de componente de precios",
    shortDescription : "Diseño para frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/FM-interactive-pricing-component/',
    githubURL : 'https://github.com/danyrszz/tip-calculator-vanillaJS',
  },
]

//ENGLISH CONTENT



const projectsEN : Projects[] = [
  {
    id : 1,
    name : "Project portfolio",
    shortDescription : "This very portfolio 😄",
    tags : ['React', 'NextJS', 'Typescript'],
    siteURL : '/',
    githubURL : 'https://github.com/danyrszz/personal-portfolio',
  },
  {
    id : 2,
    name : "Expenses/Incomes tracker",
    shortDescription : "Personal app to keep track of the expenses and incomes of a taxi unit",
    tags : ['React', 'CSS', 'Express', 'MongoDB'],
    siteURL : null,
    githubURL : 'https://github.com/danyrszz/expenses-incomes-tracker-app---MERN-stack',
    more : [
      ['title', 'Expenses/Incomes taxi tracker.' ],
      ['text','The idea of this app was conceived under the need of managing the incomes and expenses generated by a taxi car.'],
      ['text',`This project is developed as a web system under the MERN stack. It was made using web technologies such as expressJS, MongoDB and React. The system is intended for personal use. Project's fronted is deployed on render and backend is deployed on vercel.`],
      ['text',`Since this application handles personal information is not available for anyone to visit, however I show here some screenshots of the system and explain its behaviour. The code, of course, it's available on github.`],
      ['title','Sections of the app.'],
      ['subtitle','Dashboard'],
      ['image','/blog-img/2/dash.png'],
      ['text','The home page. This shows some general information, and the last 5 spends and bills.'],
      ['subtitle','Add Bill and Add Spends'],
      ['image','/blog-img/2/addspend.png'],
      ['text','These both are the sections that allows to record information on the database through a user-friendly form.'],
      ['subtitle','History > Bills'],
      ['image','/blog-img/2/bills.png'],
      ['text','This shows the recorded bills per month, allows the user to filter by month and year. A bill can be modified or deleted.'],
      ['subtitle','History > Spends'],
      ['image','/blog-img/2/spends-desktop.png'],
      ['text','Starter page of spends shows the last 10 spends, but the user can filter the information provided with several ways to filter the data. A clicked spend redirects the user to the form so it can be edited or deleted.'],
      ['text','There are three views for the spends made responsive for desktop, tablet and smartphone.'],
      ['image','/blog-img/2/spends-tablet.png'],
      ['caption','Spends tablet view'],
      ['image','/blog-img/2/spends-mobile.png'],
      ['caption','Spends smartphone view'],
      ['subtitle','Spends filter'],
      ['text','This window allows the user to select up to three different filters to show the spends. Filters can be applied single or can be combined to find a spend with precision. '],
      ['image','/blog-img/2/filter.png'],
      ['caption','Unselected filter view'],
      ['text',`Let's imagine we'd only want to view the services of the car that have cost less than $1000, and have been performed just in this 2023 year. This is how the filter would look like`],
      ['image','/blog-img/2/threefilters.png'],
      ['text','...and this would be the result'],
      ['image','/blog-img/2/filteredspends.png'],
      ['subtitle','Asset'],
      ['text',`And last but not least, we have the asset page with a nice picture of the car, and some extra information, showing the earnings (as the highlighted section. In this case negative because I haven't reached earnings yet) and the percent of the current of the investment recovery.`],
      ['image','/blog-img/2/asset.png'],
      ['title','A little more...'],
      ['text','This app can handle just one single car. This was on purpose, I had this in mind when I designed and developed the system. There were two main reasons: '],
      ['text','One: I wanted to keep this as simple as possible because I was only having one single taxi working and no more than one, therefore I needed this to be quickly completed to start keeping track of my information.'],
      ['text',`Second: I wanted to push myself to work with technologies that I didn't work with in the past. For example: I've been, as you can see in my projects below, practicing frontend skills with some basic javascript and more HTML and CSS. I wanted to pratice a little bit more of react and understand more concepts to apply on this project.`],
      ['text', `Aswell, this is a fully developed and deployed fullstack app, so I had to code not only the frontend and the responsive view of the page, but write the backend on node connected to a mongodb cluster, and learn a bit of both worlds. `]
    ]
  },
  {
    id : 3,
    name : "Weather app",
    shortDescription : "Displays weather information of a determined location.",
    tags : ['React', 'CSS', 'APIs'],
    siteURL : 'https://danyrszz.github.io/weather-app-reactjs/',
    githubURL : 'https://github.com/danyrszz/weather-app-reactjs',
    more : [
      ['title', 'Weather App' ],
      ['text',`This is a single-page app developed with react. A weather API provides the information that this frontend consumes, displaying it on a nice user interface.`],
      ['subtitle','Main sidebar.'],
      ['text',`This sidebar shows information of today's weather, such as temperature icon, real feel, date and location`],
      ['subtitle','Search sidebar.'],
      ['text',`Allows you to search any location you want, also you can select your current device location.`],
      ['subtitle','Scalebar.'],
      ['text','You can choose either celsius degrees or fahrenheit.'],
      ['subtitle','Weekly weather.'],
      ['text','Shows next six days weather information.'],
      ['subtitle','Highlights.'],
      ['text','Shows wind information, humidity, cloud and air pressure.'],
    ]

  },
  {
    id : 4,
    name : "Country Quiz",
    shortDescription : "Quiz game challenge for devchallenges.io",
    tags : ['React', 'CSS', 'APIs'],
    siteURL : 'https://danyrszz.github.io/country-quiz-react/',
    githubURL : 'https://github.com/danyrszz/country-quiz-react',
    more : [
      ['title', 'Country Quiz'],
      ['text', `A little multiple-choice quiz game, powered by a country-information API.`],
      ['text', `You have three lives, your score is updated as long as you don't make a mistake. If so, you lose a life. Three mistakes and you're out.`],
      ['text', `Have fun!`]
    ]
  },
  {
    id : 5,
    name : "Windbnb",
    shortDescription : "An Airbnb interface clone. A challenge for devchallenges.io.",
    tags : ['React', 'CSS'],
    siteURL : 'https://danyrszz.github.io/windbnb-reactJS-devchallenges/',
    githubURL : 'https://github.com/danyrszz/windbnb-reactJS-devchallenges',
    more : [
      ['title', `Windbnb`],
      ['text','This was a challenge available on devchallenges website.'],
      ['text',`It's a UI-clone of airbnb with a little functionality. There are some rentals and you are able to filter by location and number of guests.`],
      ['text',`Quite simple but a good challenge to practice some css skills and a little of JS.`],
    ]
  },
  {
    id : 6,
    name : "Advice generator",
    shortDescription : "A random advice generator app. Challenge for frontendmentor.",
    tags : ['Javascript', 'HTML', 'SASS'],
    siteURL : 'https://danyrszz.github.io/FM-advice-generator-app/',
    githubURL : 'https://github.com/danyrszz/FM-advice-generator-app',
  },
  {
    id : 7,
    name : "Codewars challenges",
    shortDescription : "Some codewars challenges repository.",
    tags : ['Javascript'],
    siteURL : null,
    githubURL : 'https://github.com/danyrszz/codewars',
  },
  {
    id : 8,
    name : "Countdown screen",
    shortDescription : "A countdown screen challenge for frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/FM-launch-countdown-timer/',
    githubURL : 'https://github.com/danyrszz/FM-launch-countdown-timer',
  },
  {
    id : 9,
    name : "Tip Calculator",
    shortDescription : "A tip calculator app. Challenge for frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/tip-calculator-vanillaJS/',
    githubURL : 'https://github.com/danyrszz/tip-calculator-vanillaJS',
  },
  {
    id : 10,
    name : "Price component design",
    shortDescription : "Design challenge for frontendmentor.",
    tags : ['Javascript','HTML','CSS'],
    siteURL : 'https://danyrszz.github.io/FM-interactive-pricing-component/',
    githubURL : 'https://github.com/danyrszz/tip-calculator-vanillaJS',
  },
]

export {projectsES, projectsEN}

